version: '3'
services:
  accountserver:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "50051:50051"
    networks:
      - dbserver_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbserver_network

networks:
  dbserver_network:
    driver: bridge
